name: Test

on:
  pull_request

jobs:
  pull_request:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y yajl-tools
      - name: Setup Python Version
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
      - name: Run tests
        run: CONCURRENCY=4 LOG_LEVEL=INFO make test
